version: '3'
services:
  apollo:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    environment:
      # PRISMA_ENDPOINT: '${PRISMA_URL}:${PRISMA_PORT}/${PRISMA_SERVICE_NAME}/${PRISMA_STAGE}'
      # PRISMA_SECRET: '${PRISMA_SECRET}'
      APOLLO_PORT: '${APOLLO_PORT}'
      APOLLO_TEST_PORT: ${APOLLO_TEST_PORT}
      JWT_SECRET: '${JWT_SECRET}'
      DB_URL: '${DB_URL}'
    volumes:
      - ./apollo/src:/app/src
    ports:
      - '${APOLLO_PORT:-8000}:${APOLLO_PORT:-8000}'
    depends_on:
      - db
    command: sh -c "npm run ${NPM_COMMAND}"
  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: 'prisma_db'
      POSTGRES_USER: ${PG_USER:-prisma}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-prisma}
    volumes:
      - db_data:/var/lib/prisma_db/data
    ports:
      - '5432:5432'
volumes:
  db_data:
