version: '3.8'
services:
  apollo:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      APOLLO_PORT: '${APOLLO_PORT}'
      APOLLO_TEST_PORT: ${APOLLO_TEST_PORT}
      JWT_SECRET: '${JWT_SECRET}'
      DB_URL: '${DB_URL}'
    volumes:
      - type: volume
        source: apollo
        target: /app
      # - ./src:/app/src
    ports:
      - '${APOLLO_PORT:-8000}:${APOLLO_PORT:-8000}'
    depends_on:
      - db
    # command: sh -c "npm run ${NPM_COMMAND}"
    command: sh -c "npm run prisma:mgs && npm run prisma:mgu && npm run prisma:gen && npm run ${NPM_COMMAND}"

  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: 'prisma_db'
      POSTGRES_USER: ${PG_USER:-prisma}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-prisma}
    volumes:
      - db_data:/var/lib/prisma_db/data
    ports:
      - 5432:5432
volumes:
  db_data:
  apollo:
